services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./local-dev/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - portal
      - api_local
      - router
    networks:
      - internal

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: polysynergy_db
      POSTGRES_USER: polysynergy_user
      POSTGRES_PASSWORD: securepassword
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    networks:
      - internal

  api_local:
    build:
      context: .
      dockerfile: ./api-local/Dockerfile
    env_file:
      - ./api-local/.env.local
    volumes:
      - ./api-local:/app
      - ./documentation:/documentation
      - ./nodes:/nodes
      - ./node_runner:/node_runner
      - ./nodes_agno:/nodes_agno
      - ./nodes_dev:/nodes_dev
    networks:
      - internal
    environment:
      - PROJECT_DB=/sqlite_data/polysynergy.db
      - CORS_ORIGINS=https://portal.polysynergy.dev
    depends_on:
      - db
      - redis

  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    volumes:
      - ./portal:/app
      - ./portal/node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      PORT: 4000
      # Update these to use the local domains
      NEXT_PUBLIC_POLYSYNERGY_API: "https://api.polysynergy.dev"
      NEXT_PUBLIC_POLYSYNERGY_WEBSOCKET_URL: "wss://api.polysynergy.dev"
    networks:
      - internal

  router:
    build:
      context: ./router
    container_name: router-service
    volumes:
      - ./router:/app
    env_file:
      - ./router/.env.local
    networks:
      - internal

volumes:
  caddy_data:
  caddy_config:
  db_data:

networks:
  internal:
    driver: bridge