version: '3.8'

services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"  # Publiek bereikbaar op poort 5432
    environment:
      POSTGRES_DB: polysynergy_db
      POSTGRES_USER: polysynergy_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      - /opt/polysynergy-orchestrator/db_data:/var/lib/postgresql/data
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3

  agno_session_db:
    image: postgres:14
    ports:
      - "5433:5432"  # Publiek bereikbaar op poort 5433
    environment:
      POSTGRES_DB: agno_session_db
      POSTGRES_USER: agno_user
      POSTGRES_PASSWORD_FILE: /run/secrets/agno_postgres_password
    secrets:
      - agno_postgres_password
    volumes:
      - /opt/polysynergy-orchestrator/agno_session_db_data:/var/lib/postgresql/data
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3

  
  redis:
    image: redis:8
    ports:
      - "6379:6379"  # Publiek bereikbaar MET wachtwoord
    secrets:
      - redis_password
    volumes:
      - redis_data:/data
      - /opt/polysynergy-orchestrator/redis/entrypoint.sh:/entrypoint.sh:ro
    command: ["sh", "/entrypoint.sh"]
    networks:
      - internal

  api_local:
    image: polysynergy-api:latest
    ports:
      - "8090:8090"
    environment:
      PROJECT_DB: /sqlite_data/polysynergy.db
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      AGNO_POSTGRES_PASSWORD_FILE: /run/secrets/agno_postgres_password
      RELOAD_DIRS: --reload-dir /app --reload-dir /nodes --reload-dir /node_runner --reload-dir /nodes_agno
      PYTHONDONTWRITEBYTECODE: 1
    env_file:
      - /opt/polysynergy-orchestrator/api-local/.env
    secrets:
      - postgres_password
      - agno_postgres_password
      - redis_password
    volumes:
      - /opt/polysynergy-orchestrator/api-local:/app
      - /opt/polysynergy-orchestrator/documentation:/documentation
      - /opt/polysynergy-orchestrator/updates:/updates
      - /opt/polysynergy-orchestrator/nodes:/nodes
      - /opt/polysynergy-orchestrator/node_runner:/node_runner
      - /opt/polysynergy-orchestrator/nodes_agno:/nodes_agno
      - api_data:/sqlite_data
    networks:
      - internal
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 30s
      timeout: 3s
      retries: 3


  router:
    image: polysynergy-router:latest
    ports:
      - "8080:8080"
    environment:
      ROUTER_ENV: production
    volumes:
      - /opt/polysynergy-orchestrator/router:/app
    networks:
      - internal
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3

  caddy:
    image: polysynergy-caddy:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      AWS_REGION: eu-central-1
    env_file:
      - /opt/polysynergy-orchestrator/.env.prod
    volumes:
      - /opt/polysynergy-orchestrator/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3

volumes:
  db_data:
    driver: local
  agno_db_data:
    driver: local
  redis_data:
    driver: local
  api_data:
    driver: local
  nodes_data:
    driver: local
  node_runner_data:
    driver: local
  nodes_agno_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local

networks:
  internal:
    driver: overlay
    attachable: true

secrets:
  postgres_password:
    external: true
  agno_postgres_password:
    external: true
  redis_password:
    external: true
  router_config:
    external: true
  aws_access_key_id:
    external: true
  aws_secret_access_key:
    external: true
