name: Deploy to Production

# Trigger deployment on push to main branch
on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      service:
        description: 'Service to deploy (api/portal/router/all)'
        required: false
        default: 'all'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/polysynergy-orchestrator

          # Pull latest code
          git pull origin main
          git submodule update --init --recursive --remote

          # Deploy based on service parameter
          if [ "${{ github.event.inputs.service }}" == "api" ]; then
            ./deploy-swarm.sh update api
          elif [ "${{ github.event.inputs.service }}" == "router" ]; then
            ./deploy-swarm.sh update router
          else
            ./deploy-swarm.sh deploy
          fi

          # Check status
          docker stack services polysynergy