name: Trigger Deployment

# Trigger webhook on push to main branch
on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      service:
        description: 'Service to deploy (api/portal/router/all)'
        required: false
        default: 'all'

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Webhook
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "X-GitHub-Event: push" \
          -H "X-Hub-Signature-256: sha256=$(echo -n '${{ toJson(github) }}' | openssl dgst -sha256 -hmac '${{ secrets.WEBHOOK_SECRET }}' -binary | xxd -p)" \
          -d '${{ toJson(github) }}' \
          ${{ secrets.WEBHOOK_URL }}/webhook

    - name: Check Deployment Status
      run: |
        echo "Webhook triggered successfully"
        echo "Check your server logs for deployment progress"
        echo "Health check: curl ${{ secrets.WEBHOOK_URL }}/health"